image: docker:dind
services:
  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://10.0.100.100:5555
  CI_REGISTRY_IMAGE: ihorman/hw-service:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}

cache:
  paths:
    - .m2/repository/
    - server/target/
    
stages:
  - build
  - test
  - package
  - deploy-topology
  - deploy-version

api-service-build:
  image: maven:3.6.3-jdk-13
  stage: build
  script: |-
        cd server
        mvn package -B -X
  retry: 2  
  only:
    changes:
      - Dockerfile
      - server/**/*
  artifacts:
    paths:
      - server/target/*.jar
      
api-service-test:
  image: maven:3-jdk-8
  stage: test
  script: "echo TEST OK"
  only:
    changes:
      - server/**/*

api-service-package:
  stage: package
  image: docker:dind
  needs: ["api-service-build"]
  services:
  - docker:dind
  script: |-
         echo Artifact to deploy: $(ls -1 ./server/target/*.jar)
         docker build -t $CI_REGISTRY_IMAGE .
         docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
         docker push $CI_REGISTRY_IMAGE
  retry: 2
  only:
    changes:
      - Dockerfile
      - server/**/*
 
deploy-topology:
  stage: deploy-topology
  image: dtzar/helm-kubectl
  script: |-
      kubectl config set-cluster k8s --server="${K8S_SERVER}";
      kubectl config set clusters.k8s.certificate-authority-data "${K8S_CA_B64}";
      kubectl config set-credentials gitlab --token="${K8S_TOKEN}";
      kubectl config set-context default --cluster=k8s --user=gitlab;
      kubectl config use-context default;
      sed -i "s/BRANCH_NAME/$CI_COMMIT_REF_NAME/g" topology/*.yaml;
      kubectl apply -f topology/namespace.yaml;
      kubectl apply -f topology/helloworld.yaml;
  only:
    changes:
      - topology/**/*


deploy-service:
  image: google/cloud-sdk
  stage: deploy-version
  script: |-
        echo "Deploying API Service"l
        echo "Executed in runnner:" $(hostname)
        kubectl config set-cluster k8s --server="${K8S_SERVER}"
        kubectl config set clusters.k8s.certificate-authority-data "${K8S_CA_B64}"
        kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
        kubectl config set-context default --cluster=k8s --user=gitlab
        kubectl config use-context default
        kubectl set image deployment hw-service hw-service=${CI_REGISTRY_IMAGE} -n ${CI_COMMIT_REF_NAME}
        echo "API Service Deployment Compleated, version:" ${CI_REGISTRY_IMAGE}

  only:
    changes:
      - server/**/*
  
